### ISSUE TITLE
Standardized Button Labels

### ISSUE THREAD

**Issue by billyhunt** [caneruguz/osf-style#12]
Button text should be standardized.

Examples
-------------

To submit a form, always use "Save" as a button label.  
To Cancel an action, use "Cancel"

**Comment by caneruguz** [comment]
Thanks Billy, very good point. It would be useful actually if you could add this and submit a PR to this repository. I would like this to be a community effort and if you have the time would help a lot if you could amend this and submit a PR. Let me know if you need help forking and working with this locally. Thanks!

**Comment by caneruguz** [comment]
I made these edits. Let's keep discussing here about other potential changes. 
http://caneruguz.github.io/osf-style/#buttons

**Comment by caneruguz** [comment]
@billyhunt can you check the section I linked and let me know if you think they are good?

**Comment by billyhunt** [comment]
There might be some confusion as to which button text to use.  Specifically:

"Back" vs "Close"
"Remove" vs "Delete"
"Learn More" vs "i"
"Settings" vs "Options"

When possible, I would remove one of the choices unless the distinction is great enough to be misleading to the user.  (for example, Back vs Close are probably different enough to both be necessary).  If they are distinct, then we could make explicit use cases for each in the guide.

"Back is to be used in any multi-step process that is forced by the osf, for example, share registration.  Not to be used in a process that the user initiates, for example, navigating to a file in a project"

**Comment by caneruguz** [comment]
I agree, can you make a PR with these changes?

**Comment by billyhunt** [comment]
Sure thing.
