### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by brianjgeiger** [caneruguz/osf-style#17]
Now that we are running PhantomJS for our Search Engine Indexing, the History and SEO section may only need to be a History section. "Because most of the interaction does not require page loads, search engines may not be able to get a sense of your content and therefore fail to index" is not accurate (unless we care about non-google search engines and we are not similarly sharing content with those engines).

**Comment by caneruguz** [comment]
Thanks Brian, this looks like a good PR to me :)  Can you make the change and send as PR? I think you can even do it over github website since it's only text change.

**Comment by caneruguz** [comment]
Made the change and removed the SEO content.
