### ISSUE TITLE
Specify anchor styles

### ISSUE THREAD

**Issue by JeffSpies** [caneruguz/osf-style#2]
This can go in the button style if you'd prefer, but we should link to that section from a TOC entry labelled anchors. I would like to see three varieties:

- One without an underline, but with a distinct color
- One with a solid underline
- One with a dashed underline

**Comment by caneruguz** [comment]
Are these varities have these attributes on hover or all the time, for instance is solid underline always on or only on hover. I'm guessing now that if there us an underline it should always be there. 
- Should underlined linsk be same color as regular links? 
- Should we remove hover effects on underlined links?

**Comment by JeffSpies** [comment]
I could see hover being relevant for links that aren't underlined but of distinct color.

What are we doing now for the most part? Is there any consistency or do we need to make a decision?

**Comment by caneruguz** [comment]
Currently if the links are not in their own element (i.e. navigation items) they are standard not underlined until hovered over type. The standard one in the guide is like that, and the other two have constant underline but they change color slightly to show they are clickable. 

I think the question will arise about when to use which of these link colors, it's better to stick to one for inline links.
