### ISSUE TITLE
Dropdown organization

### ISSUE THREAD

**Issue by csoderberg** [caneruguz/osf-style#23]
Right now it says, "Alphabetically organize your dropdowns"

While this may often be fine, depending on what the drop down is for a non-alphabetic order may make more logical sense, or may be necessary to makes sure users scan through certain response options before getting to others.

**Comment by caneruguz** [comment]
While that's true, I don't know if it's so prevalent that it needs to be in the guide? Maybe we can add a sentence or too about it? Any suggestions on what it should say? @csoderberg

**Comment by csoderberg** [comment]
I actually think the alphabetization would tend to be the less prevalent
case. In terms of where I know we use drop downs now, most of them make
have an intuitive order to them other than alphabetization (e.g.
contributor permissions, components, notification configuration settings,
wiki edit versions).

So, perhaps something like:

When using drop downs, think carefully about the ordering of the options.
Is the a hierarchical, or temporal order to the options that could be used
to order them? Are they're certain options that users should see before
others, assuming they are scanning down the list [this is actually just
good practice whether they are using drop downs, check boxes, or radical
buttons]? If none of these apply, then the drop down options should be in
alphabetical order.

On Mon, Jun 15, 2015 at 12:57 PM, Caner Uguz <notifications@github.com>
wrote:

> While that's true, I don't know if it's so prevalent that it needs to be
> in the guide? Maybe we can add a sentence or too about it? Any suggestions
> on what it should say? @csoderberg <https://github.com/csoderberg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caneruguz/osf-style/issues/23#issuecomment-112136645>.
>



-- 
Courtney Soderberg, Ph.D
Statistical and Methodological Consultant
Center for Open Science

**Comment by caneruguz** [comment]
I like that text, I'll add to the appropriate section.

**Comment by csoderberg** [comment]
So I just realized that this comment is per tenant for both selects and drop-downs I think (still not quite sure about which of the things I listed above on the OSF would be considered selects vs. drop downs)

**Comment by csoderberg** [comment]
Basically, the main point of my comment is that, when giving people options in any form (checkboxes, radical buttons, drop downs, selects) we should think about the order carefully, and alphabetical should be the option when there isn't another than makes sense.
