### ISSUE TITLE
Specify kinds of pending processes and timing of "long"

### ISSUE THREAD

**Issue by alexschiller** [caneruguz/osf-style#27]
The line of text: Pending processes should be identified if taking long

Can you be clearer about how pending processes should be identified (spinners?). 

Can you give a better estimate of what 'long' is in this context?

This is also a general comment that whenever a time (long) or an action (identified) is used it needs to be clear how long and how it is identified.

**Comment by caneruguz** [comment]
I will clarify what pending processes are but timing definitions should not be within the scope of this style guide. Strict times are hard to enforce and arbitrary. What's more important is the expected time from the user. When a user uploads a file the expectation is that it will take long, while page loads are expected to load fast. In a page load 3 seconds is long, in a file upload up to 30 seconds would still be tolerable.

**Comment by alexschiller** [comment]
I don't necessarily mean strict times because as you said, it varies. However, adding a note like you did here there clarifies that point would be beneficial I think.

**Comment by caneruguz** [comment]
Okay added to the text, thanks @alexschiller !
