### ISSUE TITLE
Specify use cases for input methods

### ISSUE THREAD

**Issue by jlcohoon** [caneruguz/osf-style#3]
A variety of input methods are used on the OSF for various reasons. Specifying when to choose a particular input method over another would be helpful. For example:

button(s) vs button group vs toggle
dropdown vs check boxes vs radio buttons
inline editing (click to edit, click button to edit)

When to require a submit button for changes would also be helpful.

**Comment by caneruguz** [comment]
@jlcohoon 
Check this: http://caneruguz.github.io/osf-style/#inputs
 and this: http://caneruguz.github.io/osf-style/#options

What kind of additions or changes should happen?
