### ISSUE TITLE
Suggestion: Do not disable Submit buttons if input is invalid

### ISSUE THREAD

**Issue by sloria** [caneruguz/osf-style#32]
This has been discussed here: https://github.com/CenterForOpenScience/osf.io/issues/1035 . I recommend adding a guideline that says not to disable form submit buttons if data are invalid. Instead, the user should be allowed to click submit and see error messages next to the bad input.

**Comment by caneruguz** [comment]
I added it to here with state of submit buttons. 
http://caneruguz.github.io/osf-style/ui.html#button-state

**Comment by sloria** [comment]
Hm, I find the examples a little misleading--they appear to suggest that you should display validation messages next to the buttons when they should be displayed next to or under the input elements.

**Comment by sloria** [comment]
Also, just to clarify:

![osf_style___ui_guidelines](https://cloud.githubusercontent.com/assets/2379650/8255007/ea02ed4a-166a-11e5-9aa7-4e43ac5aa43f.png)

Is this suggesting that the Save button is disabled *only* when there is no user input yet, and that it will be enabled when there is user input (which may or may not be invalid)?
