### ISSUE TITLE
Suggestion: Add guidelines for button colors

### ISSUE THREAD

**Issue by sloria** [caneruguz/osf-style#33]
Button colors are currently inconsistent. It would be nice to have guideline coloring buttons.

e.g. "Submit buttons should use be blue (.btn-primary)".

**Comment by caneruguz** [comment]
There is some information about this already. In here there is help on which buttons to choose and the text to use: http://caneruguz.github.io/osf-style/#buttons

Does that need more clarification?

**Comment by sloria** [comment]
Ah ok, I didn't see that section. Disregard.
