### ISSUE TITLE
Specify when to use different alert types

### ISSUE THREAD

**Issue by jlcohoon** [caneruguz/osf-style#4]
Users can be made aware of information in several ways. Most of the time, information is just given as text on the page. When an alert is needed, we sometimes use dismissible alerts, timed alerts, inline text that is timed, or modals. Including the proper use cases for each of these, as well as how much time transitory alerts stick around for, would be a good addition to the style guide.

**Comment by billyhunt** [comment]
Few more questions.  When should we modals? When should we put a message next to a field and what should it look like? Should the cursor be moved to the field that needs fixing? Should we use growl or alerts when we cannot help the user? (probably not both)

Examples

When leaving a page without the changes saved.

Modal:

Would You Like to Save Your Changes?
YES/NO

When a user has a not filled in a required field.

Growl Message:

Last Name is a required field.

Additionally, direct the user to the field with a correctly mapped message. (e.g. write "required" next to the "Last Name" field in red.)

User is a magic unicorn who only can read Alerts

Alert:

Don't Use Alerts Unless Its Absolutely Necessary!

**Comment by sloria** [comment]
Yes, along these lines, it would be good to have guidelines about how to display error messages. For example: 'Error messages for text inputs in a form should be displayed under the input element in red text after the form is submitted." or "Unexpected errors, e.g. from service outages, 500 errors, etc., should be displayed as growl-style notifications."

**Comment by caneruguz** [comment]
Can y'all check this section and let me know if it covers these concerns? It talks about feedback rather than all information so please make specific recommendations. 

http://caneruguz.github.io/osf-style/#feedback

**Comment by billyhunt** [comment]
I can’t think of a case that is not covered.  I don’t agree with all the choices, but its awesome you are making us standardize.

**Comment by sloria** [comment]
Yes, this is a good starting point. I think this issue can be closed for now.

**Comment by caneruguz** [comment]
I'm closign this, but if things are missing point out specific questions we can address. Thanks for all the feedback.
