### ISSUE TITLE
Describe formatting of warning modals

### ISSUE THREAD

**Issue by jlcohoon** [caneruguz/osf-style#5]
Warning modals are especially important on the OSF because they often tell the user about how their information is kept private or will be made public. Including a template for a warning modal (colors for submit buttons, how to label the button, if the header should be distinct from other modals, if font-awesome icons should be used ever, etc.). Could help us stay consistent in the way we format these, and ultimately make it clearer to the user when they need to pay attention.

**Comment by caneruguz** [comment]
@jlcohoon   Is this a good look?  Do you have any suggestions? 

![screen shot 2015-06-16 at 3 12 01 pm](https://cloud.githubusercontent.com/assets/1314003/8192134/1bfeb474-143a-11e5-8713-a784e62d1376.png)

**Comment by jlcohoon** [comment]
It's great! I especially like the use of delete/some specific verb instead of "okay"

**Comment by caneruguz** [comment]
Added here: http://localhost:8000/style.html#modals
