### ISSUE TITLE
explain when to show un-actionable items

### ISSUE THREAD

**Issue by jlcohoon** [caneruguz/osf-style#6]
Sometimes users are shown options they cannot select. Sometimes those options are hidden instead, but become available after an action (e.g. a submit button is shown after the user makes a selection). We might want to describe when the un-actionable items should be shown rather than hidden, and (if necessary) what to put in a tool-tip to explain the reason it cannot be clicked.

**Comment by caneruguz** [comment]
Some of these are covered, for instance hiding submit button and disabled buttons. Can you make a list of some other instances?

**Comment by jlcohoon** [comment]
What you have looks good, for showing/hiding. Sometimes we don't have a submit button at all though (e.g. the notifications settings on a project)—perhaps we should cover when an action/submit button is required in general?

**Comment by caneruguz** [comment]
I added that submit and save buttons are always required http://caneruguz.github.io/osf-style/ui.html#button-state. Is that what you mean?

**Comment by jlcohoon** [comment]
yes!
