### ISSUE TITLE
explain how to break up space

### ISSUE THREAD

**Issue by jlcohoon** [caneruguz/osf-style#7]
Text or areas are often separated on the OSF using HRs, but sometimes we use extra padding, or just insert a new header. We shoulddescribe the scenarios in which each one is preferable.

**Comment by caneruguz** [comment]
How is this? 

How to space elements:
- Use margin helpers at top and bottom of divs to separate content.
- Do NOT use HR until you tried all margin sizes for spacing. Is sections need to be further separated you can try HR tag.
- Do NOT use padding to separate vertical layout elements. USE padding to move content away from its own box, align with inner alignment of other text elements or create gutter spacing between horizontal layout elements

**Comment by jlcohoon** [comment]
great!
