### ISSUE TITLE
when to use round corners vs right angles

### ISSUE THREAD

**Issue by jlcohoon** [caneruguz/osf-style#8]
In the containers section, examples of flat boxes and round boxes are shown. When would we use the round corners rather than the right angles?

**Comment by caneruguz** [comment]
Does this cover your concern?

**Tips:**
- For general purpose use neutral background flat box.
- For menus or sidebars use the round box
- Use light or dark background depending on how much emphasis the items need to have.
- Avoid using colored backgrounds with large amounts of text. We have a white background color scheme so we rarely need to use large text with colored backgrounds.

**Comment by jlcohoon** [comment]
looks good to me!
